fix(#11): CI/CD 수정

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -50,44 +50,18 @@ jobs:
           ls -l docker-compose.yml || echo "docker-compose.yml not found in local repo"
           scp -v -o StrictHostKeyChecking=no -i private_key.pem docker-compose.yml ubuntu@${{ secrets.EC2_HOST_JIHO }}:~/docker-compose.yml
           ssh -v -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.EC2_HOST_JIHO }} << 'EOF'
-            # Docker 설치 확인
-            if ! command -v docker &> /dev/null; then
-              sudo apt update -y
-              sudo apt install -y docker.io
-              sudo systemctl start docker
-              sudo systemctl enable docker
-              sudo usermod -aG docker ubuntu
-            fi
-            docker --version
 
-            # Docker Compose 설치 확인
-            if ! command -v docker-compose &> /dev/null; then
-              sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.7/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
-              sudo chmod +x /usr/local/bin/docker-compose
-            fi
-            docker-compose --version
+          # ECR 로그인
+          sudo aws ecr get-login-password --region ap-northeast-2 | sudo docker login --username AWS --password-stdin 600627346244.dkr.ecr.ap-northeast-2.amazonaws.com || echo "ECR login failed"
 
-            # AWS CLI 설치 확인
-            if ! command -v aws &> /dev/null; then
-              sudo apt update -y
-              sudo apt install -y unzip
-              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-              unzip -o awscliv2.zip
-              sudo ./aws/install
-            fi
-            aws --version
+          # 기존 리소스 정리
+          sudo docker stop $(sudo docker ps -q) || true
+          sudo docker rm $(sudo docker ps -aq) || true
+          sudo docker rmi $(sudo docker images -q) -f || true
+          sudo docker system prune -a -f --volumes
 
-            # ECR 로그인
-            sudo aws ecr get-login-password --region ap-northeast-2 | sudo docker login --username AWS --password-stdin 600627346244.dkr.ecr.ap-northeast-2.amazonaws.com || echo "ECR login failed"
+          # 최신 이미지 Pull
+          sudo docker pull 600627346244.dkr.ecr.ap-northeast-2.amazonaws.com/plus-project:latest || echo "Failed to pull myapp image"
 
-            # 기존 리소스 정리
-            sudo docker stop $(sudo docker ps -q) || true
-            sudo docker rm $(sudo docker ps -aq) || true
-            sudo docker rmi $(sudo docker images -q) -f || true
-            sudo docker system prune -a -f --volumes
-
-            # 최신 이미지 Pull
-            sudo docker pull 600627346244.dkr.ecr.ap-northeast-2.amazonaws.com/plus-project:latest || echo "Failed to pull myapp image"
-
-            # docker-compose.yml 확인
-            ls -l ~/docker-compose.yml || echo "docker-compose.yml not found on E
+          # docker-compose.yml 확인
+          ls -l ~/docker-compose.yml || echo "docker-compose.yml not found on E
